name: Tag Master Branch

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  terraform:
    name: 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["technical-module1", "technical-module2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release Config
        run: |
          echo '{"tagFormat": v${version}-${{ matrix.module }}}' > .releaserc
          cat .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.2
          extra_plugins: |
            "@semantic-release/commit-analyzer@8.0.1"
            "@semantic-release/release-notes-generator@9.0.0"
            "@semantic-release/changelog@5.0.0"
            "@semantic-release/github@7.0.2"
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}