name: Tag Master Branch

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  terraform:
    name: 'Update Docs and Release module'
    runs-on: ubuntu-latest
    strategy:
      # Avoid to fail all pipelines with one module failed
      fail-fast: false
      # Could not release two modules at the same time, so run them sequentially
      max-parallel: 1
      matrix:
        module:
          - technical-module-a
          - technical-module-b
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to pull complete git history to check if there is changes since last commit for the module #monorepo
          fetch-depth: 0
      - name: Gather number of changes since last module commit (in the same branch)
        run: |
          export CHANGES_SINCE_LAST_MODULE_TAG=$(git diff --name-only $(git describe --match "${{ matrix.module }}*" --tags --abbrev=0)..@  --abbrev=0 -- ${{ matrix.module }} | wc -l)
          echo "::set-env name=changes_since_last_module_tag::${CHANGES_SINCE_LAST_MODULE_TAG}"
      - name: Stop here if there is no changes in module directory since last commit.
        run: echo "There is changes since last commit, go on"
        if: ${{ env.CHANGES_SINCE_LAST_MODULE_TAG }} >= 1
        # MonoRepo issue, if two modules are released at the same time, fix fast-forwards issue
      - name: Check if git is up to date with remote
        run: git pull
      - name: "Update Terraform docs"
        uses: Dirrk/terraform-docs@7353ff3 #v1.0.6
        with:
          tf_docs_working_dir: "${{ matrix.module }}/"
          tf_docs_output_file: README.md
          tf_docs_git_push: true
          tf_docs_git_commit_message: "docs: auto generated terraform docs"
      - name: Semantic Release Config
        run: |
          echo '{
                   "tagFormat":"${{ matrix.module }}-v${version}",
                   "plugins": [
                      '@semantic-release/commit-analyzer',
                      '@semantic-release/release-notes-generator',
                      '@semantic-release/changelog',
                      '@semantic-release/github'
                   ]
                }
          '> .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.2
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.0
            @semantic-release/changelog@5.0.0
            @semantic-release/github@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
