name: Tag Master Branch

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  terraform:
    name: 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - technical-module-a
        - technical-module-b
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release Config
        run: |
          echo '{
                   "tagFormat":"${{ matrix.module }}-v${version}",
                   "plugins": [
                      '@semantic-release/commit-analyzer',
                      '@semantic-release/release-notes-generator',
                      '@semantic-release/changelog',
                      '@semantic-release/github'
                   ]
                }
          '> .releaserc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.2
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.0
            @semantic-release/changelog@5.0.0
            @semantic-release/github@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
