name: Test Feature Branch

on:
  pull_request:

jobs:
  terraform_fmt:
    name: 'Terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.11.14
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  terraform-validate:
    name: 'Terraform validate'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["technical-module1", "technical-module2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.11.14
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ matrix.module }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.11.14
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ matrix.module }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
